version: '3'

services:
  api:
    build: ./api
    working_dir: /usr/src/api 
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "9991:9991"
    env_file:
      - server.env
    tty: true
    command: npm start
  redis-server:
    image: redis
  web:
    build: ./web
    working_dir: /usr/src/web
    links:
      - api:api.internal
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
    ports:
      - "7070:7070"
    tty: true
    command: npm start
