module.exports = {
    sites: [
        '01465798',
        '014670261',
        '01467042',
        '01467048',
        '01467086',
        '01467087',
        '01467200',
        '01473800',
        '01474000',
        '01474500',
        '01474501',
        '01474703',
        '01475530',
        '01475553',
        '400229075104601',
    ],
    variables: {
        TEMPERATURE_DESCRIPTION: 'Temperature, water, degrees Celsius',
        DISCHARGE_DESCRIPTION: 'Discharge, cubic feet per second',
        GAGE_HEIGHT_DESCRIPTION: 'Gage height, feet',
        CONDUCTANCE_DESCRIPTION: 'Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius',
        OXYGEN_VALUE_DESCRIPTION: 'Dissolved oxygen, water, unfiltered, milligrams per liter',
        OXYGEN_PERCENTAGE_DESCRIPTION: 'Dissolved oxygen, water, unfiltered, percent of saturation',
        PH_DESCRIPTION: 'pH, water, unfiltered, field, standard units',
        TURBIDITY_DESCRIPTION: 'Turbidity, water, unfiltered, monochrome near infra-red LED light, 780-900 nm, detection angle 90 +-2.5 degrees, formazin nephelometric units (FNU)',
        PRESSURE_DESCRIPTION: 'Barometric pressure (BP), uncorrected, pounds per square inch',
        RADIATION_DESCRIPTION: 'Photosynthetically active radiation (average flux density on a horizontal surface during measurement interval), micromoles of photons per square meter per second',
        FLUORESCENCE_DESCRIPTION: 'Chlorophyll fluorescence (fChl), water, in situ, fluorometric method, excitation at 470 +-15 nm, emission at 685 +-20 nm, relative fluorescence units (RFU)',
        PRECIPITATION_DESCRIPTION: 'Precipitation, total, inches',
        DEPTH_DESCRIPTION: 'Depth to water level, feet below land surface',
    },
};
